### ISSUE TITLE
fresh WordPress install error from index.php

### ISSUE THREAD

**Issue by goodeggclub** [searsandrew/centreforge#1]
Hello, first thank you for all your hard work. In a fresh WP install with Settings > Reading > "Your latest posts" chosen I am getting the following error.

Parse error: syntax error, unexpected '>', expecting ')' in /webroot/wp-content/themes/centreforge-master/index.php on line 22

If I set a static page the error goes away. 
Also, I can't find any documentation. Can you help me to understand how to use the theme options? I see them on the posts and pages but not sure how they integrate.
Any help is greatly appreciated.
Thanks, 
Russ

**Comment by mread1208** [comment]
Russ,

Thank you for pointing this out!  I actually stumbled across the same issue yesterday and fixed.  Had a syntax error in our index.php file.  The latest version should be stable now.

We haven't been branching our builds so our updates are going straight into the master branch.  Once we release 2.2.0 (which should be this Friday 9/18) we will start branching each release so issues like this (hopefully) don't come up in our master branch.

Also, to answer your other question.  We are currently working on some documentation for this core theme.  Keep checking back and we will release that when we have it ready!

Thanks again,
Michael
